### PR TITLE
fix: unresolved `node:util` issues when running tests

### PR DESCRIPTION
**Pull request by shazron**
## Description

~⚠️ However, this is causing journalling unit test failures now. ⚠️~ 

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by shazron** [comment]
Note that the journaling test failures also occur with jest@27.x,  and jest@28.x

**Comment by shazron** [comment]
I think the fix could be:
`jest.advanceTimersByTime(0)` -> `jest.advanceTimersByTime(1)`

I don't think jest does anything if the value is 0.

**Review by sandeep-paliwal — APPROVED** [review]
Changes look good. Lets see if this fixes the test failure issue.

**Review by sangeetha5491 — APPROVED** [review]
looks good

**Pull request merged**
